apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: exam-ibrohim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: ibrokhim06/image-task5:v1
        ports:
        - containerPort: 50051
        env:
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: LOG_LEVEL
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: GRPC_PORT
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: database
              key: DB_URI
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

