apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: exam-ibrohim
  labels:
    app: my-app
    env: production
  annotations:
    createdBy: ibrohim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 64Mi
        env:
        - name: CPU
          valueFrom:
            resourceFieldRef:
              containerName: my-container
              resource: requests.cpu
        - name: MEMORY
          valueFrom:
            resourceFieldRef:
              containerName: my-container
              resource: requests.memory

