apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: my-app-service
  namespace: exam-ibrohim
spec:
  ports:
  - port: 50051
    protocol: TCP
    targetPort: 50051
  selector:
    app: my-app
  type: NodePort
status:
  loadBalancer: {}
