apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 16.171.4.8
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2ad
  namespace: metallb-system

